/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PersonvernRouteImport } from './routes/personvern'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnnonserRouteImport } from './routes/annonser'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrukerIdRouteImport } from './routes/bruker.$id'
import { Route as AnnonseIdRouteImport } from './routes/annonse.$id'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedNyAnnonseRouteImport } from './routes/_authenticated/ny-annonse'
import { Route as AuthenticatedMineSokRouteImport } from './routes/_authenticated/mine-sok'
import { Route as AuthenticatedFavoritterRouteImport } from './routes/_authenticated/favoritter'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedMineAnnonserIndexRouteImport } from './routes/_authenticated/mine-annonser.index'
import { Route as AuthenticatedMeldingerIndexRouteImport } from './routes/_authenticated/meldinger.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedMeldingerIdRouteImport } from './routes/_authenticated/meldinger.$id'
import { Route as AuthenticatedAdminKategorierRouteImport } from './routes/_authenticated/admin/kategorier'
import { Route as AuthenticatedAdminBrukereRouteImport } from './routes/_authenticated/admin/brukere'
import { Route as ApiPublicPushDispatchRouteImport } from './routes/api/public/push/dispatch'
import { Route as AuthenticatedMineAnnonserIdRedigerRouteImport } from './routes/_authenticated/mine-annonser.$id.rediger'
import { Route as ApiPublicAuthVippsCallbackRouteImport } from './routes/api/public/auth/vipps/callback'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonvernRoute = PersonvernRouteImport.update({
  id: '/personvern',
  path: '/personvern',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnonserRoute = AnnonserRouteImport.update({
  id: '/annonser',
  path: '/annonser',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrukerIdRoute = BrukerIdRouteImport.update({
  id: '/bruker/$id',
  path: '/bruker/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnonseIdRoute = AnnonseIdRouteImport.update({
  id: '/annonse/$id',
  path: '/annonse/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNyAnnonseRoute = AuthenticatedNyAnnonseRouteImport.update({
  id: '/ny-annonse',
  path: '/ny-annonse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMineSokRoute = AuthenticatedMineSokRouteImport.update({
  id: '/mine-sok',
  path: '/mine-sok',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritterRoute = AuthenticatedFavoritterRouteImport.update({
  id: '/favoritter',
  path: '/favoritter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMineAnnonserIndexRoute =
  AuthenticatedMineAnnonserIndexRouteImport.update({
    id: '/mine-annonser/',
    path: '/mine-annonser/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeldingerIndexRoute =
  AuthenticatedMeldingerIndexRouteImport.update({
    id: '/meldinger/',
    path: '/meldinger/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedMeldingerIdRoute =
  AuthenticatedMeldingerIdRouteImport.update({
    id: '/meldinger/$id',
    path: '/meldinger/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminKategorierRoute =
  AuthenticatedAdminKategorierRouteImport.update({
    id: '/kategorier',
    path: '/kategorier',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBrukereRoute =
  AuthenticatedAdminBrukereRouteImport.update({
    id: '/brukere',
    path: '/brukere',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicPushDispatchRoute = ApiPublicPushDispatchRouteImport.update({
  id: '/api/public/push/dispatch',
  path: '/api/public/push/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMineAnnonserIdRedigerRoute =
  AuthenticatedMineAnnonserIdRedigerRouteImport.update({
    id: '/mine-annonser/$id/rediger',
    path: '/mine-annonser/$id/rediger',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAuthVippsCallbackRoute =
  ApiPublicAuthVippsCallbackRouteImport.update({
    id: '/api/public/auth/vipps/callback',
    path: '/api/public/auth/vipps/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annonser': typeof AnnonserRoute
  '/auth': typeof AuthRoute
  '/personvern': typeof PersonvernRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/favoritter': typeof AuthenticatedFavoritterRoute
  '/mine-sok': typeof AuthenticatedMineSokRoute
  '/ny-annonse': typeof AuthenticatedNyAnnonseRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/annonse/$id': typeof AnnonseIdRoute
  '/bruker/$id': typeof BrukerIdRoute
  '/admin/brukere': typeof AuthenticatedAdminBrukereRoute
  '/admin/kategorier': typeof AuthenticatedAdminKategorierRoute
  '/meldinger/$id': typeof AuthenticatedMeldingerIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/meldinger/': typeof AuthenticatedMeldingerIndexRoute
  '/mine-annonser/': typeof AuthenticatedMineAnnonserIndexRoute
  '/mine-annonser/$id/rediger': typeof AuthenticatedMineAnnonserIdRedigerRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/auth/vipps/callback': typeof ApiPublicAuthVippsCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annonser': typeof AnnonserRoute
  '/auth': typeof AuthRoute
  '/personvern': typeof PersonvernRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/favoritter': typeof AuthenticatedFavoritterRoute
  '/mine-sok': typeof AuthenticatedMineSokRoute
  '/ny-annonse': typeof AuthenticatedNyAnnonseRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/annonse/$id': typeof AnnonseIdRoute
  '/bruker/$id': typeof BrukerIdRoute
  '/admin/brukere': typeof AuthenticatedAdminBrukereRoute
  '/admin/kategorier': typeof AuthenticatedAdminKategorierRoute
  '/meldinger/$id': typeof AuthenticatedMeldingerIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/meldinger': typeof AuthenticatedMeldingerIndexRoute
  '/mine-annonser': typeof AuthenticatedMineAnnonserIndexRoute
  '/mine-annonser/$id/rediger': typeof AuthenticatedMineAnnonserIdRedigerRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/auth/vipps/callback': typeof ApiPublicAuthVippsCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/annonser': typeof AnnonserRoute
  '/auth': typeof AuthRoute
  '/personvern': typeof PersonvernRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/favoritter': typeof AuthenticatedFavoritterRoute
  '/_authenticated/mine-sok': typeof AuthenticatedMineSokRoute
  '/_authenticated/ny-annonse': typeof AuthenticatedNyAnnonseRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/annonse/$id': typeof AnnonseIdRoute
  '/bruker/$id': typeof BrukerIdRoute
  '/_authenticated/admin/brukere': typeof AuthenticatedAdminBrukereRoute
  '/_authenticated/admin/kategorier': typeof AuthenticatedAdminKategorierRoute
  '/_authenticated/meldinger/$id': typeof AuthenticatedMeldingerIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/meldinger/': typeof AuthenticatedMeldingerIndexRoute
  '/_authenticated/mine-annonser/': typeof AuthenticatedMineAnnonserIndexRoute
  '/_authenticated/mine-annonser/$id/rediger': typeof AuthenticatedMineAnnonserIdRedigerRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/auth/vipps/callback': typeof ApiPublicAuthVippsCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/annonser'
    | '/auth'
    | '/personvern'
    | '/sitemap.xml'
    | '/admin'
    | '/favoritter'
    | '/mine-sok'
    | '/ny-annonse'
    | '/profil'
    | '/annonse/$id'
    | '/bruker/$id'
    | '/admin/brukere'
    | '/admin/kategorier'
    | '/meldinger/$id'
    | '/admin/'
    | '/meldinger/'
    | '/mine-annonser/'
    | '/mine-annonser/$id/rediger'
    | '/api/public/push/dispatch'
    | '/api/public/auth/vipps/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/annonser'
    | '/auth'
    | '/personvern'
    | '/sitemap.xml'
    | '/favoritter'
    | '/mine-sok'
    | '/ny-annonse'
    | '/profil'
    | '/annonse/$id'
    | '/bruker/$id'
    | '/admin/brukere'
    | '/admin/kategorier'
    | '/meldinger/$id'
    | '/admin'
    | '/meldinger'
    | '/mine-annonser'
    | '/mine-annonser/$id/rediger'
    | '/api/public/push/dispatch'
    | '/api/public/auth/vipps/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/annonser'
    | '/auth'
    | '/personvern'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/favoritter'
    | '/_authenticated/mine-sok'
    | '/_authenticated/ny-annonse'
    | '/_authenticated/profil'
    | '/annonse/$id'
    | '/bruker/$id'
    | '/_authenticated/admin/brukere'
    | '/_authenticated/admin/kategorier'
    | '/_authenticated/meldinger/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/meldinger/'
    | '/_authenticated/mine-annonser/'
    | '/_authenticated/mine-annonser/$id/rediger'
    | '/api/public/push/dispatch'
    | '/api/public/auth/vipps/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnnonserRoute: typeof AnnonserRoute
  AuthRoute: typeof AuthRoute
  PersonvernRoute: typeof PersonvernRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AnnonseIdRoute: typeof AnnonseIdRoute
  BrukerIdRoute: typeof BrukerIdRoute
  ApiPublicPushDispatchRoute: typeof ApiPublicPushDispatchRoute
  ApiPublicAuthVippsCallbackRoute: typeof ApiPublicAuthVippsCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personvern': {
      id: '/personvern'
      path: '/personvern'
      fullPath: '/personvern'
      preLoaderRoute: typeof PersonvernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonser': {
      id: '/annonser'
      path: '/annonser'
      fullPath: '/annonser'
      preLoaderRoute: typeof AnnonserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bruker/$id': {
      id: '/bruker/$id'
      path: '/bruker/$id'
      fullPath: '/bruker/$id'
      preLoaderRoute: typeof BrukerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonse/$id': {
      id: '/annonse/$id'
      path: '/annonse/$id'
      fullPath: '/annonse/$id'
      preLoaderRoute: typeof AnnonseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ny-annonse': {
      id: '/_authenticated/ny-annonse'
      path: '/ny-annonse'
      fullPath: '/ny-annonse'
      preLoaderRoute: typeof AuthenticatedNyAnnonseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mine-sok': {
      id: '/_authenticated/mine-sok'
      path: '/mine-sok'
      fullPath: '/mine-sok'
      preLoaderRoute: typeof AuthenticatedMineSokRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritter': {
      id: '/_authenticated/favoritter'
      path: '/favoritter'
      fullPath: '/favoritter'
      preLoaderRoute: typeof AuthenticatedFavoritterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mine-annonser/': {
      id: '/_authenticated/mine-annonser/'
      path: '/mine-annonser'
      fullPath: '/mine-annonser/'
      preLoaderRoute: typeof AuthenticatedMineAnnonserIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meldinger/': {
      id: '/_authenticated/meldinger/'
      path: '/meldinger'
      fullPath: '/meldinger/'
      preLoaderRoute: typeof AuthenticatedMeldingerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/meldinger/$id': {
      id: '/_authenticated/meldinger/$id'
      path: '/meldinger/$id'
      fullPath: '/meldinger/$id'
      preLoaderRoute: typeof AuthenticatedMeldingerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/kategorier': {
      id: '/_authenticated/admin/kategorier'
      path: '/kategorier'
      fullPath: '/admin/kategorier'
      preLoaderRoute: typeof AuthenticatedAdminKategorierRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/brukere': {
      id: '/_authenticated/admin/brukere'
      path: '/brukere'
      fullPath: '/admin/brukere'
      preLoaderRoute: typeof AuthenticatedAdminBrukereRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/push/dispatch': {
      id: '/api/public/push/dispatch'
      path: '/api/public/push/dispatch'
      fullPath: '/api/public/push/dispatch'
      preLoaderRoute: typeof ApiPublicPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mine-annonser/$id/rediger': {
      id: '/_authenticated/mine-annonser/$id/rediger'
      path: '/mine-annonser/$id/rediger'
      fullPath: '/mine-annonser/$id/rediger'
      preLoaderRoute: typeof AuthenticatedMineAnnonserIdRedigerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/auth/vipps/callback': {
      id: '/api/public/auth/vipps/callback'
      path: '/api/public/auth/vipps/callback'
      fullPath: '/api/public/auth/vipps/callback'
      preLoaderRoute: typeof ApiPublicAuthVippsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminBrukereRoute: typeof AuthenticatedAdminBrukereRoute
  AuthenticatedAdminKategorierRoute: typeof AuthenticatedAdminKategorierRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminBrukereRoute: AuthenticatedAdminBrukereRoute,
    AuthenticatedAdminKategorierRoute: AuthenticatedAdminKategorierRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedFavoritterRoute: typeof AuthenticatedFavoritterRoute
  AuthenticatedMineSokRoute: typeof AuthenticatedMineSokRoute
  AuthenticatedNyAnnonseRoute: typeof AuthenticatedNyAnnonseRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedMeldingerIdRoute: typeof AuthenticatedMeldingerIdRoute
  AuthenticatedMeldingerIndexRoute: typeof AuthenticatedMeldingerIndexRoute
  AuthenticatedMineAnnonserIndexRoute: typeof AuthenticatedMineAnnonserIndexRoute
  AuthenticatedMineAnnonserIdRedigerRoute: typeof AuthenticatedMineAnnonserIdRedigerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedFavoritterRoute: AuthenticatedFavoritterRoute,
  AuthenticatedMineSokRoute: AuthenticatedMineSokRoute,
  AuthenticatedNyAnnonseRoute: AuthenticatedNyAnnonseRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedMeldingerIdRoute: AuthenticatedMeldingerIdRoute,
  AuthenticatedMeldingerIndexRoute: AuthenticatedMeldingerIndexRoute,
  AuthenticatedMineAnnonserIndexRoute: AuthenticatedMineAnnonserIndexRoute,
  AuthenticatedMineAnnonserIdRedigerRoute:
    AuthenticatedMineAnnonserIdRedigerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnnonserRoute: AnnonserRoute,
  AuthRoute: AuthRoute,
  PersonvernRoute: PersonvernRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AnnonseIdRoute: AnnonseIdRoute,
  BrukerIdRoute: BrukerIdRoute,
  ApiPublicPushDispatchRoute: ApiPublicPushDispatchRoute,
  ApiPublicAuthVippsCallbackRoute: ApiPublicAuthVippsCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
