/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KaupetCodeRouteImport } from './routes/$kaupetCode'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AnnonserRouteImport } from './routes/annonser'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BedriftsinvitasjonRouteImport } from './routes/bedriftsinvitasjon'
import { Route as BekreftEpostRouteImport } from './routes/bekreft-epost'
import { Route as NyAnnonseRouteImport } from './routes/ny-annonse'
import { Route as NyOkAnnonseRouteImport } from './routes/ny-ok-annonse'
import { Route as PersonvernRouteImport } from './routes/personvern'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TilbakestillPassordRouteImport } from './routes/tilbakestill-passord'
import { Route as VilkarRouteImport } from './routes/vilkar'
import { Route as KaupetCodeSubRouteImport } from './routes/$kaupetCode_.$sub'
import { Route as R360OpptakTokenRouteImport } from './routes/360-opptak.$token'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedBedriftRouteRouteImport } from './routes/_authenticated/bedrift/route'
import { Route as AuthenticatedFavoritterRouteImport } from './routes/_authenticated/favoritter'
import { Route as AuthenticatedMegRouteImport } from './routes/_authenticated/meg'
import { Route as AuthenticatedMineSokRouteImport } from './routes/_authenticated/mine-sok'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedVarslerRouteImport } from './routes/_authenticated/varsler'
import { Route as AnnonseListingIdRouteImport } from './routes/annonse.$listingId'
import { Route as AnnonserFilterRouteImport } from './routes/annonser_.filter'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as BedriftOrganizationIdRouteImport } from './routes/bedrift.$organizationId'
import { Route as BrukerIdRouteImport } from './routes/bruker.$id'
import { Route as OkIdRouteImport } from './routes/ok.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminBedrifterRouteImport } from './routes/_authenticated/admin/bedrifter'
import { Route as AuthenticatedAdminBrukereRouteImport } from './routes/_authenticated/admin/brukere'
import { Route as AuthenticatedAdminKategorierRouteImport } from './routes/_authenticated/admin/kategorier'
import { Route as AuthenticatedAdminKjoretoyRouteImport } from './routes/_authenticated/admin/kjoretoy'
import { Route as AuthenticatedAdminModerasjonRouteImport } from './routes/_authenticated/admin/moderasjon'
import { Route as AuthenticatedAdminProffAbonnementRouteImport } from './routes/_authenticated/admin/proff-abonnement'
import { Route as AuthenticatedAdminPromoteringerRouteImport } from './routes/_authenticated/admin/promoteringer'
import { Route as AuthenticatedAdminTilbakemeldingerRouteImport } from './routes/_authenticated/admin/tilbakemeldinger'
import { Route as AuthenticatedAdminVippsWebhooksRouteImport } from './routes/_authenticated/admin/vipps-webhooks'
import { Route as AuthenticatedBedriftIndexRouteImport } from './routes/_authenticated/bedrift/index'
import { Route as AuthenticatedBedriftVelgPlanRouteImport } from './routes/_authenticated/bedrift/velg-plan'
import { Route as AuthenticatedBekrefterPromoIdRouteImport } from './routes/_authenticated/bekrefter.$promoId'
import { Route as AuthenticatedKvitteringPromoIdRouteImport } from './routes/_authenticated/kvittering.$promoId'
import { Route as AuthenticatedMeldingerIndexRouteImport } from './routes/_authenticated/meldinger.index'
import { Route as AuthenticatedMeldingerIdRouteImport } from './routes/_authenticated/meldinger.$id'
import { Route as AuthenticatedMineAnnonserIndexRouteImport } from './routes/_authenticated/mine-annonser.index'
import { Route as ApiPublicCspReportRouteImport } from './routes/api/public/csp-report'
import { Route as ApiV1LocationsRouteImport } from './routes/api/v1/locations'
import { Route as ApiV1OpenapiDotjsonRouteImport } from './routes/api/v1/openapi[.]json'
import { Route as ApiPublicApiKeysExpiryNotifyRouteImport } from './routes/api/public/api-keys/expiry-notify'
import { Route as ApiPublicImagesProcessRouteImport } from './routes/api/public/images/process'
import { Route as ApiPublicPushDispatchRouteImport } from './routes/api/public/push/dispatch'
import { Route as ApiPublicR2CleanupRouteImport } from './routes/api/public/r2/cleanup'
import { Route as ApiPublicVippsWebhookRouteImport } from './routes/api/public/vipps/webhook'
import { Route as ApiV1CategoriesIndexRouteImport } from './routes/api/v1/categories/index'
import { Route as ApiV1ListingsIndexRouteImport } from './routes/api/v1/listings/index'
import { Route as ApiV1ListingsBatchRouteImport } from './routes/api/v1/listings/batch'
import { Route as ApiV1ListingsRenewRouteImport } from './routes/api/v1/listings/renew'
import { Route as ApiV1CategoriesIdFieldsRouteImport } from './routes/api/v1/categories/$id/fields'
import { Route as ApiV1ListingsExternalRefIndexRouteImport } from './routes/api/v1/listings/$externalRef/index'
import { Route as ApiV1ListingsExternalRefImagesRouteImport } from './routes/api/v1/listings/$externalRef/images'
import { Route as ApiV1ListingsExternalRefStatusRouteImport } from './routes/api/v1/listings/$externalRef/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KaupetCodeRoute = KaupetCodeRouteImport.update({
  id: '/$kaupetCode',
  path: '/$kaupetCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnonserRoute = AnnonserRouteImport.update({
  id: '/annonser',
  path: '/annonser',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BedriftsinvitasjonRoute = BedriftsinvitasjonRouteImport.update({
  id: '/bedriftsinvitasjon',
  path: '/bedriftsinvitasjon',
  getParentRoute: () => rootRouteImport,
} as any)
const BekreftEpostRoute = BekreftEpostRouteImport.update({
  id: '/bekreft-epost',
  path: '/bekreft-epost',
  getParentRoute: () => rootRouteImport,
} as any)
const NyAnnonseRoute = NyAnnonseRouteImport.update({
  id: '/ny-annonse',
  path: '/ny-annonse',
  getParentRoute: () => rootRouteImport,
} as any)
const NyOkAnnonseRoute = NyOkAnnonseRouteImport.update({
  id: '/ny-ok-annonse',
  path: '/ny-ok-annonse',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonvernRoute = PersonvernRouteImport.update({
  id: '/personvern',
  path: '/personvern',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TilbakestillPassordRoute = TilbakestillPassordRouteImport.update({
  id: '/tilbakestill-passord',
  path: '/tilbakestill-passord',
  getParentRoute: () => rootRouteImport,
} as any)
const VilkarRoute = VilkarRouteImport.update({
  id: '/vilkar',
  path: '/vilkar',
  getParentRoute: () => rootRouteImport,
} as any)
const KaupetCodeSubRoute = KaupetCodeSubRouteImport.update({
  id: '/$kaupetCode_/$sub',
  path: '/$kaupetCode/$sub',
  getParentRoute: () => rootRouteImport,
} as any)
const R360OpptakTokenRoute = R360OpptakTokenRouteImport.update({
  id: '/360-opptak/$token',
  path: '/360-opptak/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBedriftRouteRoute =
  AuthenticatedBedriftRouteRouteImport.update({
    id: '/bedrift',
    path: '/bedrift',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFavoritterRoute = AuthenticatedFavoritterRouteImport.update({
  id: '/favoritter',
  path: '/favoritter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMegRoute = AuthenticatedMegRouteImport.update({
  id: '/meg',
  path: '/meg',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMineSokRoute = AuthenticatedMineSokRouteImport.update({
  id: '/mine-sok',
  path: '/mine-sok',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVarslerRoute = AuthenticatedVarslerRouteImport.update({
  id: '/varsler',
  path: '/varsler',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AnnonseListingIdRoute = AnnonseListingIdRouteImport.update({
  id: '/annonse/$listingId',
  path: '/annonse/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnonserFilterRoute = AnnonserFilterRouteImport.update({
  id: '/annonser_/filter',
  path: '/annonser/filter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const BedriftOrganizationIdRoute = BedriftOrganizationIdRouteImport.update({
  id: '/bedrift/$organizationId',
  path: '/bedrift/$organizationId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrukerIdRoute = BrukerIdRouteImport.update({
  id: '/bruker/$id',
  path: '/bruker/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OkIdRoute = OkIdRouteImport.update({
  id: '/ok/$id',
  path: '/ok/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminBedrifterRoute =
  AuthenticatedAdminBedrifterRouteImport.update({
    id: '/bedrifter',
    path: '/bedrifter',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBrukereRoute =
  AuthenticatedAdminBrukereRouteImport.update({
    id: '/brukere',
    path: '/brukere',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKategorierRoute =
  AuthenticatedAdminKategorierRouteImport.update({
    id: '/kategorier',
    path: '/kategorier',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKjoretoyRoute =
  AuthenticatedAdminKjoretoyRouteImport.update({
    id: '/kjoretoy',
    path: '/kjoretoy',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminModerasjonRoute =
  AuthenticatedAdminModerasjonRouteImport.update({
    id: '/moderasjon',
    path: '/moderasjon',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProffAbonnementRoute =
  AuthenticatedAdminProffAbonnementRouteImport.update({
    id: '/proff-abonnement',
    path: '/proff-abonnement',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPromoteringerRoute =
  AuthenticatedAdminPromoteringerRouteImport.update({
    id: '/promoteringer',
    path: '/promoteringer',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTilbakemeldingerRoute =
  AuthenticatedAdminTilbakemeldingerRouteImport.update({
    id: '/tilbakemeldinger',
    path: '/tilbakemeldinger',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminVippsWebhooksRoute =
  AuthenticatedAdminVippsWebhooksRouteImport.update({
    id: '/vipps-webhooks',
    path: '/vipps-webhooks',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedBedriftIndexRoute =
  AuthenticatedBedriftIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBedriftRouteRoute,
  } as any)
const AuthenticatedBedriftVelgPlanRoute =
  AuthenticatedBedriftVelgPlanRouteImport.update({
    id: '/velg-plan',
    path: '/velg-plan',
    getParentRoute: () => AuthenticatedBedriftRouteRoute,
  } as any)
const AuthenticatedBekrefterPromoIdRoute =
  AuthenticatedBekrefterPromoIdRouteImport.update({
    id: '/bekrefter/$promoId',
    path: '/bekrefter/$promoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKvitteringPromoIdRoute =
  AuthenticatedKvitteringPromoIdRouteImport.update({
    id: '/kvittering/$promoId',
    path: '/kvittering/$promoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeldingerIndexRoute =
  AuthenticatedMeldingerIndexRouteImport.update({
    id: '/meldinger/',
    path: '/meldinger/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeldingerIdRoute =
  AuthenticatedMeldingerIdRouteImport.update({
    id: '/meldinger/$id',
    path: '/meldinger/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMineAnnonserIndexRoute =
  AuthenticatedMineAnnonserIndexRouteImport.update({
    id: '/mine-annonser/',
    path: '/mine-annonser/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCspReportRoute = ApiPublicCspReportRouteImport.update({
  id: '/api/public/csp-report',
  path: '/api/public/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LocationsRoute = ApiV1LocationsRouteImport.update({
  id: '/api/v1/locations',
  path: '/api/v1/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiDotjsonRoute = ApiV1OpenapiDotjsonRouteImport.update({
  id: '/api/v1/openapi.json',
  path: '/api/v1/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApiKeysExpiryNotifyRoute =
  ApiPublicApiKeysExpiryNotifyRouteImport.update({
    id: '/api/public/api-keys/expiry-notify',
    path: '/api/public/api-keys/expiry-notify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicImagesProcessRoute = ApiPublicImagesProcessRouteImport.update({
  id: '/api/public/images/process',
  path: '/api/public/images/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushDispatchRoute = ApiPublicPushDispatchRouteImport.update({
  id: '/api/public/push/dispatch',
  path: '/api/public/push/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicR2CleanupRoute = ApiPublicR2CleanupRouteImport.update({
  id: '/api/public/r2/cleanup',
  path: '/api/public/r2/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVippsWebhookRoute = ApiPublicVippsWebhookRouteImport.update({
  id: '/api/public/vipps/webhook',
  path: '/api/public/vipps/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CategoriesIndexRoute = ApiV1CategoriesIndexRouteImport.update({
  id: '/api/v1/categories/',
  path: '/api/v1/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ListingsIndexRoute = ApiV1ListingsIndexRouteImport.update({
  id: '/api/v1/listings/',
  path: '/api/v1/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ListingsBatchRoute = ApiV1ListingsBatchRouteImport.update({
  id: '/api/v1/listings/batch',
  path: '/api/v1/listings/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ListingsRenewRoute = ApiV1ListingsRenewRouteImport.update({
  id: '/api/v1/listings/renew',
  path: '/api/v1/listings/renew',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CategoriesIdFieldsRoute = ApiV1CategoriesIdFieldsRouteImport.update({
  id: '/api/v1/categories/$id/fields',
  path: '/api/v1/categories/$id/fields',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ListingsExternalRefIndexRoute =
  ApiV1ListingsExternalRefIndexRouteImport.update({
    id: '/api/v1/listings/$externalRef/',
    path: '/api/v1/listings/$externalRef/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ListingsExternalRefImagesRoute =
  ApiV1ListingsExternalRefImagesRouteImport.update({
    id: '/api/v1/listings/$externalRef/images',
    path: '/api/v1/listings/$externalRef/images',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ListingsExternalRefStatusRoute =
  ApiV1ListingsExternalRefStatusRouteImport.update({
    id: '/api/v1/listings/$externalRef/status',
    path: '/api/v1/listings/$externalRef/status',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$kaupetCode': typeof KaupetCodeRoute
  '/annonser': typeof AnnonserRoute
  '/auth': typeof AuthRoute
  '/bedriftsinvitasjon': typeof BedriftsinvitasjonRoute
  '/bekreft-epost': typeof BekreftEpostRoute
  '/ny-annonse': typeof NyAnnonseRoute
  '/ny-ok-annonse': typeof NyOkAnnonseRoute
  '/personvern': typeof PersonvernRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tilbakestill-passord': typeof TilbakestillPassordRoute
  '/vilkar': typeof VilkarRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/bedrift': typeof AuthenticatedBedriftRouteRouteWithChildren
  '/$kaupetCode/$sub': typeof KaupetCodeSubRoute
  '/360-opptak/$token': typeof R360OpptakTokenRoute
  '/favoritter': typeof AuthenticatedFavoritterRoute
  '/meg': typeof AuthenticatedMegRoute
  '/mine-sok': typeof AuthenticatedMineSokRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/varsler': typeof AuthenticatedVarslerRoute
  '/annonse/$listingId': typeof AnnonseListingIdRoute
  '/annonser/filter': typeof AnnonserFilterRoute
  '/api/mcp': typeof ApiMcpRoute
  '/bedrift/$organizationId': typeof BedriftOrganizationIdRoute
  '/bruker/$id': typeof BrukerIdRoute
  '/ok/$id': typeof OkIdRoute
  '/admin/bedrifter': typeof AuthenticatedAdminBedrifterRoute
  '/admin/brukere': typeof AuthenticatedAdminBrukereRoute
  '/admin/kategorier': typeof AuthenticatedAdminKategorierRoute
  '/admin/kjoretoy': typeof AuthenticatedAdminKjoretoyRoute
  '/admin/moderasjon': typeof AuthenticatedAdminModerasjonRoute
  '/admin/proff-abonnement': typeof AuthenticatedAdminProffAbonnementRoute
  '/admin/promoteringer': typeof AuthenticatedAdminPromoteringerRoute
  '/admin/tilbakemeldinger': typeof AuthenticatedAdminTilbakemeldingerRoute
  '/admin/vipps-webhooks': typeof AuthenticatedAdminVippsWebhooksRoute
  '/bedrift/velg-plan': typeof AuthenticatedBedriftVelgPlanRoute
  '/bekrefter/$promoId': typeof AuthenticatedBekrefterPromoIdRoute
  '/kvittering/$promoId': typeof AuthenticatedKvitteringPromoIdRoute
  '/meldinger/$id': typeof AuthenticatedMeldingerIdRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/v1/locations': typeof ApiV1LocationsRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/bedrift/': typeof AuthenticatedBedriftIndexRoute
  '/meldinger/': typeof AuthenticatedMeldingerIndexRoute
  '/mine-annonser/': typeof AuthenticatedMineAnnonserIndexRoute
  '/api/public/api-keys/expiry-notify': typeof ApiPublicApiKeysExpiryNotifyRoute
  '/api/public/images/process': typeof ApiPublicImagesProcessRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/r2/cleanup': typeof ApiPublicR2CleanupRoute
  '/api/public/vipps/webhook': typeof ApiPublicVippsWebhookRoute
  '/api/v1/listings/batch': typeof ApiV1ListingsBatchRoute
  '/api/v1/listings/renew': typeof ApiV1ListingsRenewRoute
  '/api/v1/categories/': typeof ApiV1CategoriesIndexRoute
  '/api/v1/listings/': typeof ApiV1ListingsIndexRoute
  '/api/v1/categories/$id/fields': typeof ApiV1CategoriesIdFieldsRoute
  '/api/v1/listings/$externalRef/images': typeof ApiV1ListingsExternalRefImagesRoute
  '/api/v1/listings/$externalRef/status': typeof ApiV1ListingsExternalRefStatusRoute
  '/api/v1/listings/$externalRef/': typeof ApiV1ListingsExternalRefIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$kaupetCode': typeof KaupetCodeRoute
  '/annonser': typeof AnnonserRoute
  '/auth': typeof AuthRoute
  '/bedriftsinvitasjon': typeof BedriftsinvitasjonRoute
  '/bekreft-epost': typeof BekreftEpostRoute
  '/ny-annonse': typeof NyAnnonseRoute
  '/ny-ok-annonse': typeof NyOkAnnonseRoute
  '/personvern': typeof PersonvernRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tilbakestill-passord': typeof TilbakestillPassordRoute
  '/vilkar': typeof VilkarRoute
  '/$kaupetCode/$sub': typeof KaupetCodeSubRoute
  '/360-opptak/$token': typeof R360OpptakTokenRoute
  '/favoritter': typeof AuthenticatedFavoritterRoute
  '/meg': typeof AuthenticatedMegRoute
  '/mine-sok': typeof AuthenticatedMineSokRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/varsler': typeof AuthenticatedVarslerRoute
  '/annonse/$listingId': typeof AnnonseListingIdRoute
  '/annonser/filter': typeof AnnonserFilterRoute
  '/api/mcp': typeof ApiMcpRoute
  '/bedrift/$organizationId': typeof BedriftOrganizationIdRoute
  '/bruker/$id': typeof BrukerIdRoute
  '/ok/$id': typeof OkIdRoute
  '/admin/bedrifter': typeof AuthenticatedAdminBedrifterRoute
  '/admin/brukere': typeof AuthenticatedAdminBrukereRoute
  '/admin/kategorier': typeof AuthenticatedAdminKategorierRoute
  '/admin/kjoretoy': typeof AuthenticatedAdminKjoretoyRoute
  '/admin/moderasjon': typeof AuthenticatedAdminModerasjonRoute
  '/admin/proff-abonnement': typeof AuthenticatedAdminProffAbonnementRoute
  '/admin/promoteringer': typeof AuthenticatedAdminPromoteringerRoute
  '/admin/tilbakemeldinger': typeof AuthenticatedAdminTilbakemeldingerRoute
  '/admin/vipps-webhooks': typeof AuthenticatedAdminVippsWebhooksRoute
  '/bedrift/velg-plan': typeof AuthenticatedBedriftVelgPlanRoute
  '/bekrefter/$promoId': typeof AuthenticatedBekrefterPromoIdRoute
  '/kvittering/$promoId': typeof AuthenticatedKvitteringPromoIdRoute
  '/meldinger/$id': typeof AuthenticatedMeldingerIdRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/v1/locations': typeof ApiV1LocationsRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/bedrift': typeof AuthenticatedBedriftIndexRoute
  '/meldinger': typeof AuthenticatedMeldingerIndexRoute
  '/mine-annonser': typeof AuthenticatedMineAnnonserIndexRoute
  '/api/public/api-keys/expiry-notify': typeof ApiPublicApiKeysExpiryNotifyRoute
  '/api/public/images/process': typeof ApiPublicImagesProcessRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/r2/cleanup': typeof ApiPublicR2CleanupRoute
  '/api/public/vipps/webhook': typeof ApiPublicVippsWebhookRoute
  '/api/v1/listings/batch': typeof ApiV1ListingsBatchRoute
  '/api/v1/listings/renew': typeof ApiV1ListingsRenewRoute
  '/api/v1/categories': typeof ApiV1CategoriesIndexRoute
  '/api/v1/listings': typeof ApiV1ListingsIndexRoute
  '/api/v1/categories/$id/fields': typeof ApiV1CategoriesIdFieldsRoute
  '/api/v1/listings/$externalRef/images': typeof ApiV1ListingsExternalRefImagesRoute
  '/api/v1/listings/$externalRef/status': typeof ApiV1ListingsExternalRefStatusRoute
  '/api/v1/listings/$externalRef': typeof ApiV1ListingsExternalRefIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$kaupetCode': typeof KaupetCodeRoute
  '/annonser': typeof AnnonserRoute
  '/auth': typeof AuthRoute
  '/bedriftsinvitasjon': typeof BedriftsinvitasjonRoute
  '/bekreft-epost': typeof BekreftEpostRoute
  '/ny-annonse': typeof NyAnnonseRoute
  '/ny-ok-annonse': typeof NyOkAnnonseRoute
  '/personvern': typeof PersonvernRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tilbakestill-passord': typeof TilbakestillPassordRoute
  '/vilkar': typeof VilkarRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/bedrift': typeof AuthenticatedBedriftRouteRouteWithChildren
  '/$kaupetCode_/$sub': typeof KaupetCodeSubRoute
  '/360-opptak/$token': typeof R360OpptakTokenRoute
  '/_authenticated/favoritter': typeof AuthenticatedFavoritterRoute
  '/_authenticated/meg': typeof AuthenticatedMegRoute
  '/_authenticated/mine-sok': typeof AuthenticatedMineSokRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/varsler': typeof AuthenticatedVarslerRoute
  '/annonse/$listingId': typeof AnnonseListingIdRoute
  '/annonser_/filter': typeof AnnonserFilterRoute
  '/api/mcp': typeof ApiMcpRoute
  '/bedrift/$organizationId': typeof BedriftOrganizationIdRoute
  '/bruker/$id': typeof BrukerIdRoute
  '/ok/$id': typeof OkIdRoute
  '/_authenticated/admin/bedrifter': typeof AuthenticatedAdminBedrifterRoute
  '/_authenticated/admin/brukere': typeof AuthenticatedAdminBrukereRoute
  '/_authenticated/admin/kategorier': typeof AuthenticatedAdminKategorierRoute
  '/_authenticated/admin/kjoretoy': typeof AuthenticatedAdminKjoretoyRoute
  '/_authenticated/admin/moderasjon': typeof AuthenticatedAdminModerasjonRoute
  '/_authenticated/admin/proff-abonnement': typeof AuthenticatedAdminProffAbonnementRoute
  '/_authenticated/admin/promoteringer': typeof AuthenticatedAdminPromoteringerRoute
  '/_authenticated/admin/tilbakemeldinger': typeof AuthenticatedAdminTilbakemeldingerRoute
  '/_authenticated/admin/vipps-webhooks': typeof AuthenticatedAdminVippsWebhooksRoute
  '/_authenticated/bedrift/velg-plan': typeof AuthenticatedBedriftVelgPlanRoute
  '/_authenticated/bekrefter/$promoId': typeof AuthenticatedBekrefterPromoIdRoute
  '/_authenticated/kvittering/$promoId': typeof AuthenticatedKvitteringPromoIdRoute
  '/_authenticated/meldinger/$id': typeof AuthenticatedMeldingerIdRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/v1/locations': typeof ApiV1LocationsRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/bedrift/': typeof AuthenticatedBedriftIndexRoute
  '/_authenticated/meldinger/': typeof AuthenticatedMeldingerIndexRoute
  '/_authenticated/mine-annonser/': typeof AuthenticatedMineAnnonserIndexRoute
  '/api/public/api-keys/expiry-notify': typeof ApiPublicApiKeysExpiryNotifyRoute
  '/api/public/images/process': typeof ApiPublicImagesProcessRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/r2/cleanup': typeof ApiPublicR2CleanupRoute
  '/api/public/vipps/webhook': typeof ApiPublicVippsWebhookRoute
  '/api/v1/listings/batch': typeof ApiV1ListingsBatchRoute
  '/api/v1/listings/renew': typeof ApiV1ListingsRenewRoute
  '/api/v1/categories/': typeof ApiV1CategoriesIndexRoute
  '/api/v1/listings/': typeof ApiV1ListingsIndexRoute
  '/api/v1/categories/$id/fields': typeof ApiV1CategoriesIdFieldsRoute
  '/api/v1/listings/$externalRef/images': typeof ApiV1ListingsExternalRefImagesRoute
  '/api/v1/listings/$externalRef/status': typeof ApiV1ListingsExternalRefStatusRoute
  '/api/v1/listings/$externalRef/': typeof ApiV1ListingsExternalRefIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$kaupetCode'
    | '/annonser'
    | '/auth'
    | '/bedriftsinvitasjon'
    | '/bekreft-epost'
    | '/ny-annonse'
    | '/ny-ok-annonse'
    | '/personvern'
    | '/sitemap.xml'
    | '/tilbakestill-passord'
    | '/vilkar'
    | '/admin'
    | '/bedrift'
    | '/$kaupetCode/$sub'
    | '/360-opptak/$token'
    | '/favoritter'
    | '/meg'
    | '/mine-sok'
    | '/profil'
    | '/varsler'
    | '/annonse/$listingId'
    | '/annonser/filter'
    | '/api/mcp'
    | '/bedrift/$organizationId'
    | '/bruker/$id'
    | '/ok/$id'
    | '/admin/bedrifter'
    | '/admin/brukere'
    | '/admin/kategorier'
    | '/admin/kjoretoy'
    | '/admin/moderasjon'
    | '/admin/proff-abonnement'
    | '/admin/promoteringer'
    | '/admin/tilbakemeldinger'
    | '/admin/vipps-webhooks'
    | '/bedrift/velg-plan'
    | '/bekrefter/$promoId'
    | '/kvittering/$promoId'
    | '/meldinger/$id'
    | '/api/public/csp-report'
    | '/api/v1/locations'
    | '/api/v1/openapi.json'
    | '/admin/'
    | '/bedrift/'
    | '/meldinger/'
    | '/mine-annonser/'
    | '/api/public/api-keys/expiry-notify'
    | '/api/public/images/process'
    | '/api/public/push/dispatch'
    | '/api/public/r2/cleanup'
    | '/api/public/vipps/webhook'
    | '/api/v1/listings/batch'
    | '/api/v1/listings/renew'
    | '/api/v1/categories/'
    | '/api/v1/listings/'
    | '/api/v1/categories/$id/fields'
    | '/api/v1/listings/$externalRef/images'
    | '/api/v1/listings/$externalRef/status'
    | '/api/v1/listings/$externalRef/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$kaupetCode'
    | '/annonser'
    | '/auth'
    | '/bedriftsinvitasjon'
    | '/bekreft-epost'
    | '/ny-annonse'
    | '/ny-ok-annonse'
    | '/personvern'
    | '/sitemap.xml'
    | '/tilbakestill-passord'
    | '/vilkar'
    | '/$kaupetCode/$sub'
    | '/360-opptak/$token'
    | '/favoritter'
    | '/meg'
    | '/mine-sok'
    | '/profil'
    | '/varsler'
    | '/annonse/$listingId'
    | '/annonser/filter'
    | '/api/mcp'
    | '/bedrift/$organizationId'
    | '/bruker/$id'
    | '/ok/$id'
    | '/admin/bedrifter'
    | '/admin/brukere'
    | '/admin/kategorier'
    | '/admin/kjoretoy'
    | '/admin/moderasjon'
    | '/admin/proff-abonnement'
    | '/admin/promoteringer'
    | '/admin/tilbakemeldinger'
    | '/admin/vipps-webhooks'
    | '/bedrift/velg-plan'
    | '/bekrefter/$promoId'
    | '/kvittering/$promoId'
    | '/meldinger/$id'
    | '/api/public/csp-report'
    | '/api/v1/locations'
    | '/api/v1/openapi.json'
    | '/admin'
    | '/bedrift'
    | '/meldinger'
    | '/mine-annonser'
    | '/api/public/api-keys/expiry-notify'
    | '/api/public/images/process'
    | '/api/public/push/dispatch'
    | '/api/public/r2/cleanup'
    | '/api/public/vipps/webhook'
    | '/api/v1/listings/batch'
    | '/api/v1/listings/renew'
    | '/api/v1/categories'
    | '/api/v1/listings'
    | '/api/v1/categories/$id/fields'
    | '/api/v1/listings/$externalRef/images'
    | '/api/v1/listings/$externalRef/status'
    | '/api/v1/listings/$externalRef'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$kaupetCode'
    | '/annonser'
    | '/auth'
    | '/bedriftsinvitasjon'
    | '/bekreft-epost'
    | '/ny-annonse'
    | '/ny-ok-annonse'
    | '/personvern'
    | '/sitemap.xml'
    | '/tilbakestill-passord'
    | '/vilkar'
    | '/_authenticated/admin'
    | '/_authenticated/bedrift'
    | '/$kaupetCode_/$sub'
    | '/360-opptak/$token'
    | '/_authenticated/favoritter'
    | '/_authenticated/meg'
    | '/_authenticated/mine-sok'
    | '/_authenticated/profil'
    | '/_authenticated/varsler'
    | '/annonse/$listingId'
    | '/annonser_/filter'
    | '/api/mcp'
    | '/bedrift/$organizationId'
    | '/bruker/$id'
    | '/ok/$id'
    | '/_authenticated/admin/bedrifter'
    | '/_authenticated/admin/brukere'
    | '/_authenticated/admin/kategorier'
    | '/_authenticated/admin/kjoretoy'
    | '/_authenticated/admin/moderasjon'
    | '/_authenticated/admin/proff-abonnement'
    | '/_authenticated/admin/promoteringer'
    | '/_authenticated/admin/tilbakemeldinger'
    | '/_authenticated/admin/vipps-webhooks'
    | '/_authenticated/bedrift/velg-plan'
    | '/_authenticated/bekrefter/$promoId'
    | '/_authenticated/kvittering/$promoId'
    | '/_authenticated/meldinger/$id'
    | '/api/public/csp-report'
    | '/api/v1/locations'
    | '/api/v1/openapi.json'
    | '/_authenticated/admin/'
    | '/_authenticated/bedrift/'
    | '/_authenticated/meldinger/'
    | '/_authenticated/mine-annonser/'
    | '/api/public/api-keys/expiry-notify'
    | '/api/public/images/process'
    | '/api/public/push/dispatch'
    | '/api/public/r2/cleanup'
    | '/api/public/vipps/webhook'
    | '/api/v1/listings/batch'
    | '/api/v1/listings/renew'
    | '/api/v1/categories/'
    | '/api/v1/listings/'
    | '/api/v1/categories/$id/fields'
    | '/api/v1/listings/$externalRef/images'
    | '/api/v1/listings/$externalRef/status'
    | '/api/v1/listings/$externalRef/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  KaupetCodeRoute: typeof KaupetCodeRoute
  AnnonserRoute: typeof AnnonserRoute
  AuthRoute: typeof AuthRoute
  BedriftsinvitasjonRoute: typeof BedriftsinvitasjonRoute
  BekreftEpostRoute: typeof BekreftEpostRoute
  NyAnnonseRoute: typeof NyAnnonseRoute
  NyOkAnnonseRoute: typeof NyOkAnnonseRoute
  PersonvernRoute: typeof PersonvernRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TilbakestillPassordRoute: typeof TilbakestillPassordRoute
  VilkarRoute: typeof VilkarRoute
  KaupetCodeSubRoute: typeof KaupetCodeSubRoute
  R360OpptakTokenRoute: typeof R360OpptakTokenRoute
  AnnonseListingIdRoute: typeof AnnonseListingIdRoute
  AnnonserFilterRoute: typeof AnnonserFilterRoute
  ApiMcpRoute: typeof ApiMcpRoute
  BedriftOrganizationIdRoute: typeof BedriftOrganizationIdRoute
  BrukerIdRoute: typeof BrukerIdRoute
  OkIdRoute: typeof OkIdRoute
  ApiPublicCspReportRoute: typeof ApiPublicCspReportRoute
  ApiV1LocationsRoute: typeof ApiV1LocationsRoute
  ApiV1OpenapiDotjsonRoute: typeof ApiV1OpenapiDotjsonRoute
  ApiPublicApiKeysExpiryNotifyRoute: typeof ApiPublicApiKeysExpiryNotifyRoute
  ApiPublicImagesProcessRoute: typeof ApiPublicImagesProcessRoute
  ApiPublicPushDispatchRoute: typeof ApiPublicPushDispatchRoute
  ApiPublicR2CleanupRoute: typeof ApiPublicR2CleanupRoute
  ApiPublicVippsWebhookRoute: typeof ApiPublicVippsWebhookRoute
  ApiV1ListingsBatchRoute: typeof ApiV1ListingsBatchRoute
  ApiV1ListingsRenewRoute: typeof ApiV1ListingsRenewRoute
  ApiV1CategoriesIndexRoute: typeof ApiV1CategoriesIndexRoute
  ApiV1ListingsIndexRoute: typeof ApiV1ListingsIndexRoute
  ApiV1CategoriesIdFieldsRoute: typeof ApiV1CategoriesIdFieldsRoute
  ApiV1ListingsExternalRefImagesRoute: typeof ApiV1ListingsExternalRefImagesRoute
  ApiV1ListingsExternalRefStatusRoute: typeof ApiV1ListingsExternalRefStatusRoute
  ApiV1ListingsExternalRefIndexRoute: typeof ApiV1ListingsExternalRefIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$kaupetCode': {
      id: '/$kaupetCode'
      path: '/$kaupetCode'
      fullPath: '/$kaupetCode'
      preLoaderRoute: typeof KaupetCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonser': {
      id: '/annonser'
      path: '/annonser'
      fullPath: '/annonser'
      preLoaderRoute: typeof AnnonserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bedriftsinvitasjon': {
      id: '/bedriftsinvitasjon'
      path: '/bedriftsinvitasjon'
      fullPath: '/bedriftsinvitasjon'
      preLoaderRoute: typeof BedriftsinvitasjonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bekreft-epost': {
      id: '/bekreft-epost'
      path: '/bekreft-epost'
      fullPath: '/bekreft-epost'
      preLoaderRoute: typeof BekreftEpostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ny-annonse': {
      id: '/ny-annonse'
      path: '/ny-annonse'
      fullPath: '/ny-annonse'
      preLoaderRoute: typeof NyAnnonseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ny-ok-annonse': {
      id: '/ny-ok-annonse'
      path: '/ny-ok-annonse'
      fullPath: '/ny-ok-annonse'
      preLoaderRoute: typeof NyOkAnnonseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personvern': {
      id: '/personvern'
      path: '/personvern'
      fullPath: '/personvern'
      preLoaderRoute: typeof PersonvernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tilbakestill-passord': {
      id: '/tilbakestill-passord'
      path: '/tilbakestill-passord'
      fullPath: '/tilbakestill-passord'
      preLoaderRoute: typeof TilbakestillPassordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vilkar': {
      id: '/vilkar'
      path: '/vilkar'
      fullPath: '/vilkar'
      preLoaderRoute: typeof VilkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$kaupetCode_/$sub': {
      id: '/$kaupetCode_/$sub'
      path: '/$kaupetCode/$sub'
      fullPath: '/$kaupetCode/$sub'
      preLoaderRoute: typeof KaupetCodeSubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/360-opptak/$token': {
      id: '/360-opptak/$token'
      path: '/360-opptak/$token'
      fullPath: '/360-opptak/$token'
      preLoaderRoute: typeof R360OpptakTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bedrift': {
      id: '/_authenticated/bedrift'
      path: '/bedrift'
      fullPath: '/bedrift'
      preLoaderRoute: typeof AuthenticatedBedriftRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritter': {
      id: '/_authenticated/favoritter'
      path: '/favoritter'
      fullPath: '/favoritter'
      preLoaderRoute: typeof AuthenticatedFavoritterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meg': {
      id: '/_authenticated/meg'
      path: '/meg'
      fullPath: '/meg'
      preLoaderRoute: typeof AuthenticatedMegRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mine-sok': {
      id: '/_authenticated/mine-sok'
      path: '/mine-sok'
      fullPath: '/mine-sok'
      preLoaderRoute: typeof AuthenticatedMineSokRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/varsler': {
      id: '/_authenticated/varsler'
      path: '/varsler'
      fullPath: '/varsler'
      preLoaderRoute: typeof AuthenticatedVarslerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/annonse/$listingId': {
      id: '/annonse/$listingId'
      path: '/annonse/$listingId'
      fullPath: '/annonse/$listingId'
      preLoaderRoute: typeof AnnonseListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonser_/filter': {
      id: '/annonser_/filter'
      path: '/annonser/filter'
      fullPath: '/annonser/filter'
      preLoaderRoute: typeof AnnonserFilterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bedrift/$organizationId': {
      id: '/bedrift/$organizationId'
      path: '/bedrift/$organizationId'
      fullPath: '/bedrift/$organizationId'
      preLoaderRoute: typeof BedriftOrganizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bruker/$id': {
      id: '/bruker/$id'
      path: '/bruker/$id'
      fullPath: '/bruker/$id'
      preLoaderRoute: typeof BrukerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ok/$id': {
      id: '/ok/$id'
      path: '/ok/$id'
      fullPath: '/ok/$id'
      preLoaderRoute: typeof OkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bedrifter': {
      id: '/_authenticated/admin/bedrifter'
      path: '/bedrifter'
      fullPath: '/admin/bedrifter'
      preLoaderRoute: typeof AuthenticatedAdminBedrifterRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/brukere': {
      id: '/_authenticated/admin/brukere'
      path: '/brukere'
      fullPath: '/admin/brukere'
      preLoaderRoute: typeof AuthenticatedAdminBrukereRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kategorier': {
      id: '/_authenticated/admin/kategorier'
      path: '/kategorier'
      fullPath: '/admin/kategorier'
      preLoaderRoute: typeof AuthenticatedAdminKategorierRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kjoretoy': {
      id: '/_authenticated/admin/kjoretoy'
      path: '/kjoretoy'
      fullPath: '/admin/kjoretoy'
      preLoaderRoute: typeof AuthenticatedAdminKjoretoyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/moderasjon': {
      id: '/_authenticated/admin/moderasjon'
      path: '/moderasjon'
      fullPath: '/admin/moderasjon'
      preLoaderRoute: typeof AuthenticatedAdminModerasjonRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/proff-abonnement': {
      id: '/_authenticated/admin/proff-abonnement'
      path: '/proff-abonnement'
      fullPath: '/admin/proff-abonnement'
      preLoaderRoute: typeof AuthenticatedAdminProffAbonnementRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/promoteringer': {
      id: '/_authenticated/admin/promoteringer'
      path: '/promoteringer'
      fullPath: '/admin/promoteringer'
      preLoaderRoute: typeof AuthenticatedAdminPromoteringerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tilbakemeldinger': {
      id: '/_authenticated/admin/tilbakemeldinger'
      path: '/tilbakemeldinger'
      fullPath: '/admin/tilbakemeldinger'
      preLoaderRoute: typeof AuthenticatedAdminTilbakemeldingerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/vipps-webhooks': {
      id: '/_authenticated/admin/vipps-webhooks'
      path: '/vipps-webhooks'
      fullPath: '/admin/vipps-webhooks'
      preLoaderRoute: typeof AuthenticatedAdminVippsWebhooksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/bedrift/': {
      id: '/_authenticated/bedrift/'
      path: '/'
      fullPath: '/bedrift/'
      preLoaderRoute: typeof AuthenticatedBedriftIndexRouteImport
      parentRoute: typeof AuthenticatedBedriftRouteRoute
    }
    '/_authenticated/bedrift/velg-plan': {
      id: '/_authenticated/bedrift/velg-plan'
      path: '/velg-plan'
      fullPath: '/bedrift/velg-plan'
      preLoaderRoute: typeof AuthenticatedBedriftVelgPlanRouteImport
      parentRoute: typeof AuthenticatedBedriftRouteRoute
    }
    '/_authenticated/bekrefter/$promoId': {
      id: '/_authenticated/bekrefter/$promoId'
      path: '/bekrefter/$promoId'
      fullPath: '/bekrefter/$promoId'
      preLoaderRoute: typeof AuthenticatedBekrefterPromoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kvittering/$promoId': {
      id: '/_authenticated/kvittering/$promoId'
      path: '/kvittering/$promoId'
      fullPath: '/kvittering/$promoId'
      preLoaderRoute: typeof AuthenticatedKvitteringPromoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meldinger/': {
      id: '/_authenticated/meldinger/'
      path: '/meldinger'
      fullPath: '/meldinger/'
      preLoaderRoute: typeof AuthenticatedMeldingerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meldinger/$id': {
      id: '/_authenticated/meldinger/$id'
      path: '/meldinger/$id'
      fullPath: '/meldinger/$id'
      preLoaderRoute: typeof AuthenticatedMeldingerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mine-annonser/': {
      id: '/_authenticated/mine-annonser/'
      path: '/mine-annonser'
      fullPath: '/mine-annonser/'
      preLoaderRoute: typeof AuthenticatedMineAnnonserIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/csp-report': {
      id: '/api/public/csp-report'
      path: '/api/public/csp-report'
      fullPath: '/api/public/csp-report'
      preLoaderRoute: typeof ApiPublicCspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/locations': {
      id: '/api/v1/locations'
      path: '/api/v1/locations'
      fullPath: '/api/v1/locations'
      preLoaderRoute: typeof ApiV1LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi.json': {
      id: '/api/v1/openapi.json'
      path: '/api/v1/openapi.json'
      fullPath: '/api/v1/openapi.json'
      preLoaderRoute: typeof ApiV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/api-keys/expiry-notify': {
      id: '/api/public/api-keys/expiry-notify'
      path: '/api/public/api-keys/expiry-notify'
      fullPath: '/api/public/api-keys/expiry-notify'
      preLoaderRoute: typeof ApiPublicApiKeysExpiryNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/images/process': {
      id: '/api/public/images/process'
      path: '/api/public/images/process'
      fullPath: '/api/public/images/process'
      preLoaderRoute: typeof ApiPublicImagesProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/dispatch': {
      id: '/api/public/push/dispatch'
      path: '/api/public/push/dispatch'
      fullPath: '/api/public/push/dispatch'
      preLoaderRoute: typeof ApiPublicPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/r2/cleanup': {
      id: '/api/public/r2/cleanup'
      path: '/api/public/r2/cleanup'
      fullPath: '/api/public/r2/cleanup'
      preLoaderRoute: typeof ApiPublicR2CleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vipps/webhook': {
      id: '/api/public/vipps/webhook'
      path: '/api/public/vipps/webhook'
      fullPath: '/api/public/vipps/webhook'
      preLoaderRoute: typeof ApiPublicVippsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/categories/': {
      id: '/api/v1/categories/'
      path: '/api/v1/categories'
      fullPath: '/api/v1/categories/'
      preLoaderRoute: typeof ApiV1CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/listings/': {
      id: '/api/v1/listings/'
      path: '/api/v1/listings'
      fullPath: '/api/v1/listings/'
      preLoaderRoute: typeof ApiV1ListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/listings/batch': {
      id: '/api/v1/listings/batch'
      path: '/api/v1/listings/batch'
      fullPath: '/api/v1/listings/batch'
      preLoaderRoute: typeof ApiV1ListingsBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/listings/renew': {
      id: '/api/v1/listings/renew'
      path: '/api/v1/listings/renew'
      fullPath: '/api/v1/listings/renew'
      preLoaderRoute: typeof ApiV1ListingsRenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/categories/$id/fields': {
      id: '/api/v1/categories/$id/fields'
      path: '/api/v1/categories/$id/fields'
      fullPath: '/api/v1/categories/$id/fields'
      preLoaderRoute: typeof ApiV1CategoriesIdFieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/listings/$externalRef/': {
      id: '/api/v1/listings/$externalRef/'
      path: '/api/v1/listings/$externalRef'
      fullPath: '/api/v1/listings/$externalRef/'
      preLoaderRoute: typeof ApiV1ListingsExternalRefIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/listings/$externalRef/images': {
      id: '/api/v1/listings/$externalRef/images'
      path: '/api/v1/listings/$externalRef/images'
      fullPath: '/api/v1/listings/$externalRef/images'
      preLoaderRoute: typeof ApiV1ListingsExternalRefImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/listings/$externalRef/status': {
      id: '/api/v1/listings/$externalRef/status'
      path: '/api/v1/listings/$externalRef/status'
      fullPath: '/api/v1/listings/$externalRef/status'
      preLoaderRoute: typeof ApiV1ListingsExternalRefStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminBedrifterRoute: typeof AuthenticatedAdminBedrifterRoute
  AuthenticatedAdminBrukereRoute: typeof AuthenticatedAdminBrukereRoute
  AuthenticatedAdminKategorierRoute: typeof AuthenticatedAdminKategorierRoute
  AuthenticatedAdminKjoretoyRoute: typeof AuthenticatedAdminKjoretoyRoute
  AuthenticatedAdminModerasjonRoute: typeof AuthenticatedAdminModerasjonRoute
  AuthenticatedAdminProffAbonnementRoute: typeof AuthenticatedAdminProffAbonnementRoute
  AuthenticatedAdminPromoteringerRoute: typeof AuthenticatedAdminPromoteringerRoute
  AuthenticatedAdminTilbakemeldingerRoute: typeof AuthenticatedAdminTilbakemeldingerRoute
  AuthenticatedAdminVippsWebhooksRoute: typeof AuthenticatedAdminVippsWebhooksRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminBedrifterRoute: AuthenticatedAdminBedrifterRoute,
    AuthenticatedAdminBrukereRoute: AuthenticatedAdminBrukereRoute,
    AuthenticatedAdminKategorierRoute: AuthenticatedAdminKategorierRoute,
    AuthenticatedAdminKjoretoyRoute: AuthenticatedAdminKjoretoyRoute,
    AuthenticatedAdminModerasjonRoute: AuthenticatedAdminModerasjonRoute,
    AuthenticatedAdminProffAbonnementRoute:
      AuthenticatedAdminProffAbonnementRoute,
    AuthenticatedAdminPromoteringerRoute: AuthenticatedAdminPromoteringerRoute,
    AuthenticatedAdminTilbakemeldingerRoute:
      AuthenticatedAdminTilbakemeldingerRoute,
    AuthenticatedAdminVippsWebhooksRoute: AuthenticatedAdminVippsWebhooksRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedBedriftRouteRouteChildren {
  AuthenticatedBedriftVelgPlanRoute: typeof AuthenticatedBedriftVelgPlanRoute
  AuthenticatedBedriftIndexRoute: typeof AuthenticatedBedriftIndexRoute
}

const AuthenticatedBedriftRouteRouteChildren: AuthenticatedBedriftRouteRouteChildren =
  {
    AuthenticatedBedriftVelgPlanRoute: AuthenticatedBedriftVelgPlanRoute,
    AuthenticatedBedriftIndexRoute: AuthenticatedBedriftIndexRoute,
  }

const AuthenticatedBedriftRouteRouteWithChildren =
  AuthenticatedBedriftRouteRoute._addFileChildren(
    AuthenticatedBedriftRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedBedriftRouteRoute: typeof AuthenticatedBedriftRouteRouteWithChildren
  AuthenticatedFavoritterRoute: typeof AuthenticatedFavoritterRoute
  AuthenticatedMegRoute: typeof AuthenticatedMegRoute
  AuthenticatedMineSokRoute: typeof AuthenticatedMineSokRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedVarslerRoute: typeof AuthenticatedVarslerRoute
  AuthenticatedBekrefterPromoIdRoute: typeof AuthenticatedBekrefterPromoIdRoute
  AuthenticatedKvitteringPromoIdRoute: typeof AuthenticatedKvitteringPromoIdRoute
  AuthenticatedMeldingerIdRoute: typeof AuthenticatedMeldingerIdRoute
  AuthenticatedMeldingerIndexRoute: typeof AuthenticatedMeldingerIndexRoute
  AuthenticatedMineAnnonserIndexRoute: typeof AuthenticatedMineAnnonserIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedBedriftRouteRoute: AuthenticatedBedriftRouteRouteWithChildren,
  AuthenticatedFavoritterRoute: AuthenticatedFavoritterRoute,
  AuthenticatedMegRoute: AuthenticatedMegRoute,
  AuthenticatedMineSokRoute: AuthenticatedMineSokRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedVarslerRoute: AuthenticatedVarslerRoute,
  AuthenticatedBekrefterPromoIdRoute: AuthenticatedBekrefterPromoIdRoute,
  AuthenticatedKvitteringPromoIdRoute: AuthenticatedKvitteringPromoIdRoute,
  AuthenticatedMeldingerIdRoute: AuthenticatedMeldingerIdRoute,
  AuthenticatedMeldingerIndexRoute: AuthenticatedMeldingerIndexRoute,
  AuthenticatedMineAnnonserIndexRoute: AuthenticatedMineAnnonserIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  KaupetCodeRoute: KaupetCodeRoute,
  AnnonserRoute: AnnonserRoute,
  AuthRoute: AuthRoute,
  BedriftsinvitasjonRoute: BedriftsinvitasjonRoute,
  BekreftEpostRoute: BekreftEpostRoute,
  NyAnnonseRoute: NyAnnonseRoute,
  NyOkAnnonseRoute: NyOkAnnonseRoute,
  PersonvernRoute: PersonvernRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TilbakestillPassordRoute: TilbakestillPassordRoute,
  VilkarRoute: VilkarRoute,
  KaupetCodeSubRoute: KaupetCodeSubRoute,
  R360OpptakTokenRoute: R360OpptakTokenRoute,
  AnnonseListingIdRoute: AnnonseListingIdRoute,
  AnnonserFilterRoute: AnnonserFilterRoute,
  ApiMcpRoute: ApiMcpRoute,
  BedriftOrganizationIdRoute: BedriftOrganizationIdRoute,
  BrukerIdRoute: BrukerIdRoute,
  OkIdRoute: OkIdRoute,
  ApiPublicCspReportRoute: ApiPublicCspReportRoute,
  ApiV1LocationsRoute: ApiV1LocationsRoute,
  ApiV1OpenapiDotjsonRoute: ApiV1OpenapiDotjsonRoute,
  ApiPublicApiKeysExpiryNotifyRoute: ApiPublicApiKeysExpiryNotifyRoute,
  ApiPublicImagesProcessRoute: ApiPublicImagesProcessRoute,
  ApiPublicPushDispatchRoute: ApiPublicPushDispatchRoute,
  ApiPublicR2CleanupRoute: ApiPublicR2CleanupRoute,
  ApiPublicVippsWebhookRoute: ApiPublicVippsWebhookRoute,
  ApiV1ListingsBatchRoute: ApiV1ListingsBatchRoute,
  ApiV1ListingsRenewRoute: ApiV1ListingsRenewRoute,
  ApiV1CategoriesIndexRoute: ApiV1CategoriesIndexRoute,
  ApiV1ListingsIndexRoute: ApiV1ListingsIndexRoute,
  ApiV1CategoriesIdFieldsRoute: ApiV1CategoriesIdFieldsRoute,
  ApiV1ListingsExternalRefImagesRoute: ApiV1ListingsExternalRefImagesRoute,
  ApiV1ListingsExternalRefStatusRoute: ApiV1ListingsExternalRefStatusRoute,
  ApiV1ListingsExternalRefIndexRoute: ApiV1ListingsExternalRefIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
