/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VilkarRouteImport } from './routes/vilkar'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PersonvernRouteImport } from './routes/personvern'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnnonserRouteImport } from './routes/annonser'
import { Route as KaupetCodeRouteImport } from './routes/$kaupetCode'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrukerIdRouteImport } from './routes/bruker.$id'
import { Route as AnnonseListingIdRouteImport } from './routes/annonse.$listingId'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedNyAnnonseRouteImport } from './routes/_authenticated/ny-annonse'
import { Route as AuthenticatedMineSokRouteImport } from './routes/_authenticated/mine-sok'
import { Route as AuthenticatedFavoritterRouteImport } from './routes/_authenticated/favoritter'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedMineAnnonserIndexRouteImport } from './routes/_authenticated/mine-annonser.index'
import { Route as AuthenticatedMeldingerIndexRouteImport } from './routes/_authenticated/meldinger.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedMeldingerIdRouteImport } from './routes/_authenticated/meldinger.$id'
import { Route as AuthenticatedKvitteringPromoIdRouteImport } from './routes/_authenticated/kvittering.$promoId'
import { Route as AuthenticatedBekrefterPromoIdRouteImport } from './routes/_authenticated/bekrefter.$promoId'
import { Route as AuthenticatedAdminVippsWebhooksRouteImport } from './routes/_authenticated/admin/vipps-webhooks'
import { Route as AuthenticatedAdminPromoteringerRouteImport } from './routes/_authenticated/admin/promoteringer'
import { Route as AuthenticatedAdminModerasjonRouteImport } from './routes/_authenticated/admin/moderasjon'
import { Route as AuthenticatedAdminKategorierRouteImport } from './routes/_authenticated/admin/kategorier'
import { Route as AuthenticatedAdminBrukereRouteImport } from './routes/_authenticated/admin/brukere'
import { Route as ApiPublicVippsWebhookRouteImport } from './routes/api/public/vipps/webhook'
import { Route as ApiPublicPushDispatchRouteImport } from './routes/api/public/push/dispatch'
import { Route as AuthenticatedMineAnnonserIdRedigerRouteImport } from './routes/_authenticated/mine-annonser.$id.rediger'

const VilkarRoute = VilkarRouteImport.update({
  id: '/vilkar',
  path: '/vilkar',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonvernRoute = PersonvernRouteImport.update({
  id: '/personvern',
  path: '/personvern',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnonserRoute = AnnonserRouteImport.update({
  id: '/annonser',
  path: '/annonser',
  getParentRoute: () => rootRouteImport,
} as any)
const KaupetCodeRoute = KaupetCodeRouteImport.update({
  id: '/$kaupetCode',
  path: '/$kaupetCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrukerIdRoute = BrukerIdRouteImport.update({
  id: '/bruker/$id',
  path: '/bruker/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnonseListingIdRoute = AnnonseListingIdRouteImport.update({
  id: '/annonse/$listingId',
  path: '/annonse/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNyAnnonseRoute = AuthenticatedNyAnnonseRouteImport.update({
  id: '/ny-annonse',
  path: '/ny-annonse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMineSokRoute = AuthenticatedMineSokRouteImport.update({
  id: '/mine-sok',
  path: '/mine-sok',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritterRoute = AuthenticatedFavoritterRouteImport.update({
  id: '/favoritter',
  path: '/favoritter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMineAnnonserIndexRoute =
  AuthenticatedMineAnnonserIndexRouteImport.update({
    id: '/mine-annonser/',
    path: '/mine-annonser/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeldingerIndexRoute =
  AuthenticatedMeldingerIndexRouteImport.update({
    id: '/meldinger/',
    path: '/meldinger/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedMeldingerIdRoute =
  AuthenticatedMeldingerIdRouteImport.update({
    id: '/meldinger/$id',
    path: '/meldinger/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKvitteringPromoIdRoute =
  AuthenticatedKvitteringPromoIdRouteImport.update({
    id: '/kvittering/$promoId',
    path: '/kvittering/$promoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBekrefterPromoIdRoute =
  AuthenticatedBekrefterPromoIdRouteImport.update({
    id: '/bekrefter/$promoId',
    path: '/bekrefter/$promoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVippsWebhooksRoute =
  AuthenticatedAdminVippsWebhooksRouteImport.update({
    id: '/vipps-webhooks',
    path: '/vipps-webhooks',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPromoteringerRoute =
  AuthenticatedAdminPromoteringerRouteImport.update({
    id: '/promoteringer',
    path: '/promoteringer',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminModerasjonRoute =
  AuthenticatedAdminModerasjonRouteImport.update({
    id: '/moderasjon',
    path: '/moderasjon',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKategorierRoute =
  AuthenticatedAdminKategorierRouteImport.update({
    id: '/kategorier',
    path: '/kategorier',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBrukereRoute =
  AuthenticatedAdminBrukereRouteImport.update({
    id: '/brukere',
    path: '/brukere',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicVippsWebhookRoute = ApiPublicVippsWebhookRouteImport.update({
  id: '/api/public/vipps/webhook',
  path: '/api/public/vipps/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushDispatchRoute = ApiPublicPushDispatchRouteImport.update({
  id: '/api/public/push/dispatch',
  path: '/api/public/push/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMineAnnonserIdRedigerRoute =
  AuthenticatedMineAnnonserIdRedigerRouteImport.update({
    id: '/mine-annonser/$id/rediger',
    path: '/mine-annonser/$id/rediger',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$kaupetCode': typeof KaupetCodeRoute
  '/annonser': typeof AnnonserRoute
  '/auth': typeof AuthRoute
  '/personvern': typeof PersonvernRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vilkar': typeof VilkarRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/favoritter': typeof AuthenticatedFavoritterRoute
  '/mine-sok': typeof AuthenticatedMineSokRoute
  '/ny-annonse': typeof AuthenticatedNyAnnonseRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/annonse/$listingId': typeof AnnonseListingIdRoute
  '/bruker/$id': typeof BrukerIdRoute
  '/admin/brukere': typeof AuthenticatedAdminBrukereRoute
  '/admin/kategorier': typeof AuthenticatedAdminKategorierRoute
  '/admin/moderasjon': typeof AuthenticatedAdminModerasjonRoute
  '/admin/promoteringer': typeof AuthenticatedAdminPromoteringerRoute
  '/admin/vipps-webhooks': typeof AuthenticatedAdminVippsWebhooksRoute
  '/bekrefter/$promoId': typeof AuthenticatedBekrefterPromoIdRoute
  '/kvittering/$promoId': typeof AuthenticatedKvitteringPromoIdRoute
  '/meldinger/$id': typeof AuthenticatedMeldingerIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/meldinger/': typeof AuthenticatedMeldingerIndexRoute
  '/mine-annonser/': typeof AuthenticatedMineAnnonserIndexRoute
  '/mine-annonser/$id/rediger': typeof AuthenticatedMineAnnonserIdRedigerRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/vipps/webhook': typeof ApiPublicVippsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$kaupetCode': typeof KaupetCodeRoute
  '/annonser': typeof AnnonserRoute
  '/auth': typeof AuthRoute
  '/personvern': typeof PersonvernRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vilkar': typeof VilkarRoute
  '/favoritter': typeof AuthenticatedFavoritterRoute
  '/mine-sok': typeof AuthenticatedMineSokRoute
  '/ny-annonse': typeof AuthenticatedNyAnnonseRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/annonse/$listingId': typeof AnnonseListingIdRoute
  '/bruker/$id': typeof BrukerIdRoute
  '/admin/brukere': typeof AuthenticatedAdminBrukereRoute
  '/admin/kategorier': typeof AuthenticatedAdminKategorierRoute
  '/admin/moderasjon': typeof AuthenticatedAdminModerasjonRoute
  '/admin/promoteringer': typeof AuthenticatedAdminPromoteringerRoute
  '/admin/vipps-webhooks': typeof AuthenticatedAdminVippsWebhooksRoute
  '/bekrefter/$promoId': typeof AuthenticatedBekrefterPromoIdRoute
  '/kvittering/$promoId': typeof AuthenticatedKvitteringPromoIdRoute
  '/meldinger/$id': typeof AuthenticatedMeldingerIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/meldinger': typeof AuthenticatedMeldingerIndexRoute
  '/mine-annonser': typeof AuthenticatedMineAnnonserIndexRoute
  '/mine-annonser/$id/rediger': typeof AuthenticatedMineAnnonserIdRedigerRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/vipps/webhook': typeof ApiPublicVippsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$kaupetCode': typeof KaupetCodeRoute
  '/annonser': typeof AnnonserRoute
  '/auth': typeof AuthRoute
  '/personvern': typeof PersonvernRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vilkar': typeof VilkarRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/favoritter': typeof AuthenticatedFavoritterRoute
  '/_authenticated/mine-sok': typeof AuthenticatedMineSokRoute
  '/_authenticated/ny-annonse': typeof AuthenticatedNyAnnonseRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/annonse/$listingId': typeof AnnonseListingIdRoute
  '/bruker/$id': typeof BrukerIdRoute
  '/_authenticated/admin/brukere': typeof AuthenticatedAdminBrukereRoute
  '/_authenticated/admin/kategorier': typeof AuthenticatedAdminKategorierRoute
  '/_authenticated/admin/moderasjon': typeof AuthenticatedAdminModerasjonRoute
  '/_authenticated/admin/promoteringer': typeof AuthenticatedAdminPromoteringerRoute
  '/_authenticated/admin/vipps-webhooks': typeof AuthenticatedAdminVippsWebhooksRoute
  '/_authenticated/bekrefter/$promoId': typeof AuthenticatedBekrefterPromoIdRoute
  '/_authenticated/kvittering/$promoId': typeof AuthenticatedKvitteringPromoIdRoute
  '/_authenticated/meldinger/$id': typeof AuthenticatedMeldingerIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/meldinger/': typeof AuthenticatedMeldingerIndexRoute
  '/_authenticated/mine-annonser/': typeof AuthenticatedMineAnnonserIndexRoute
  '/_authenticated/mine-annonser/$id/rediger': typeof AuthenticatedMineAnnonserIdRedigerRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/vipps/webhook': typeof ApiPublicVippsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$kaupetCode'
    | '/annonser'
    | '/auth'
    | '/personvern'
    | '/sitemap.xml'
    | '/vilkar'
    | '/admin'
    | '/favoritter'
    | '/mine-sok'
    | '/ny-annonse'
    | '/profil'
    | '/annonse/$listingId'
    | '/bruker/$id'
    | '/admin/brukere'
    | '/admin/kategorier'
    | '/admin/moderasjon'
    | '/admin/promoteringer'
    | '/admin/vipps-webhooks'
    | '/bekrefter/$promoId'
    | '/kvittering/$promoId'
    | '/meldinger/$id'
    | '/admin/'
    | '/meldinger/'
    | '/mine-annonser/'
    | '/mine-annonser/$id/rediger'
    | '/api/public/push/dispatch'
    | '/api/public/vipps/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$kaupetCode'
    | '/annonser'
    | '/auth'
    | '/personvern'
    | '/sitemap.xml'
    | '/vilkar'
    | '/favoritter'
    | '/mine-sok'
    | '/ny-annonse'
    | '/profil'
    | '/annonse/$listingId'
    | '/bruker/$id'
    | '/admin/brukere'
    | '/admin/kategorier'
    | '/admin/moderasjon'
    | '/admin/promoteringer'
    | '/admin/vipps-webhooks'
    | '/bekrefter/$promoId'
    | '/kvittering/$promoId'
    | '/meldinger/$id'
    | '/admin'
    | '/meldinger'
    | '/mine-annonser'
    | '/mine-annonser/$id/rediger'
    | '/api/public/push/dispatch'
    | '/api/public/vipps/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$kaupetCode'
    | '/annonser'
    | '/auth'
    | '/personvern'
    | '/sitemap.xml'
    | '/vilkar'
    | '/_authenticated/admin'
    | '/_authenticated/favoritter'
    | '/_authenticated/mine-sok'
    | '/_authenticated/ny-annonse'
    | '/_authenticated/profil'
    | '/annonse/$listingId'
    | '/bruker/$id'
    | '/_authenticated/admin/brukere'
    | '/_authenticated/admin/kategorier'
    | '/_authenticated/admin/moderasjon'
    | '/_authenticated/admin/promoteringer'
    | '/_authenticated/admin/vipps-webhooks'
    | '/_authenticated/bekrefter/$promoId'
    | '/_authenticated/kvittering/$promoId'
    | '/_authenticated/meldinger/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/meldinger/'
    | '/_authenticated/mine-annonser/'
    | '/_authenticated/mine-annonser/$id/rediger'
    | '/api/public/push/dispatch'
    | '/api/public/vipps/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  KaupetCodeRoute: typeof KaupetCodeRoute
  AnnonserRoute: typeof AnnonserRoute
  AuthRoute: typeof AuthRoute
  PersonvernRoute: typeof PersonvernRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VilkarRoute: typeof VilkarRoute
  AnnonseListingIdRoute: typeof AnnonseListingIdRoute
  BrukerIdRoute: typeof BrukerIdRoute
  ApiPublicPushDispatchRoute: typeof ApiPublicPushDispatchRoute
  ApiPublicVippsWebhookRoute: typeof ApiPublicVippsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vilkar': {
      id: '/vilkar'
      path: '/vilkar'
      fullPath: '/vilkar'
      preLoaderRoute: typeof VilkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personvern': {
      id: '/personvern'
      path: '/personvern'
      fullPath: '/personvern'
      preLoaderRoute: typeof PersonvernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonser': {
      id: '/annonser'
      path: '/annonser'
      fullPath: '/annonser'
      preLoaderRoute: typeof AnnonserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$kaupetCode': {
      id: '/$kaupetCode'
      path: '/$kaupetCode'
      fullPath: '/$kaupetCode'
      preLoaderRoute: typeof KaupetCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bruker/$id': {
      id: '/bruker/$id'
      path: '/bruker/$id'
      fullPath: '/bruker/$id'
      preLoaderRoute: typeof BrukerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonse/$listingId': {
      id: '/annonse/$listingId'
      path: '/annonse/$listingId'
      fullPath: '/annonse/$listingId'
      preLoaderRoute: typeof AnnonseListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ny-annonse': {
      id: '/_authenticated/ny-annonse'
      path: '/ny-annonse'
      fullPath: '/ny-annonse'
      preLoaderRoute: typeof AuthenticatedNyAnnonseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mine-sok': {
      id: '/_authenticated/mine-sok'
      path: '/mine-sok'
      fullPath: '/mine-sok'
      preLoaderRoute: typeof AuthenticatedMineSokRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritter': {
      id: '/_authenticated/favoritter'
      path: '/favoritter'
      fullPath: '/favoritter'
      preLoaderRoute: typeof AuthenticatedFavoritterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mine-annonser/': {
      id: '/_authenticated/mine-annonser/'
      path: '/mine-annonser'
      fullPath: '/mine-annonser/'
      preLoaderRoute: typeof AuthenticatedMineAnnonserIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meldinger/': {
      id: '/_authenticated/meldinger/'
      path: '/meldinger'
      fullPath: '/meldinger/'
      preLoaderRoute: typeof AuthenticatedMeldingerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/meldinger/$id': {
      id: '/_authenticated/meldinger/$id'
      path: '/meldinger/$id'
      fullPath: '/meldinger/$id'
      preLoaderRoute: typeof AuthenticatedMeldingerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kvittering/$promoId': {
      id: '/_authenticated/kvittering/$promoId'
      path: '/kvittering/$promoId'
      fullPath: '/kvittering/$promoId'
      preLoaderRoute: typeof AuthenticatedKvitteringPromoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bekrefter/$promoId': {
      id: '/_authenticated/bekrefter/$promoId'
      path: '/bekrefter/$promoId'
      fullPath: '/bekrefter/$promoId'
      preLoaderRoute: typeof AuthenticatedBekrefterPromoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/vipps-webhooks': {
      id: '/_authenticated/admin/vipps-webhooks'
      path: '/vipps-webhooks'
      fullPath: '/admin/vipps-webhooks'
      preLoaderRoute: typeof AuthenticatedAdminVippsWebhooksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/promoteringer': {
      id: '/_authenticated/admin/promoteringer'
      path: '/promoteringer'
      fullPath: '/admin/promoteringer'
      preLoaderRoute: typeof AuthenticatedAdminPromoteringerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/moderasjon': {
      id: '/_authenticated/admin/moderasjon'
      path: '/moderasjon'
      fullPath: '/admin/moderasjon'
      preLoaderRoute: typeof AuthenticatedAdminModerasjonRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kategorier': {
      id: '/_authenticated/admin/kategorier'
      path: '/kategorier'
      fullPath: '/admin/kategorier'
      preLoaderRoute: typeof AuthenticatedAdminKategorierRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/brukere': {
      id: '/_authenticated/admin/brukere'
      path: '/brukere'
      fullPath: '/admin/brukere'
      preLoaderRoute: typeof AuthenticatedAdminBrukereRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/vipps/webhook': {
      id: '/api/public/vipps/webhook'
      path: '/api/public/vipps/webhook'
      fullPath: '/api/public/vipps/webhook'
      preLoaderRoute: typeof ApiPublicVippsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/dispatch': {
      id: '/api/public/push/dispatch'
      path: '/api/public/push/dispatch'
      fullPath: '/api/public/push/dispatch'
      preLoaderRoute: typeof ApiPublicPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mine-annonser/$id/rediger': {
      id: '/_authenticated/mine-annonser/$id/rediger'
      path: '/mine-annonser/$id/rediger'
      fullPath: '/mine-annonser/$id/rediger'
      preLoaderRoute: typeof AuthenticatedMineAnnonserIdRedigerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminBrukereRoute: typeof AuthenticatedAdminBrukereRoute
  AuthenticatedAdminKategorierRoute: typeof AuthenticatedAdminKategorierRoute
  AuthenticatedAdminModerasjonRoute: typeof AuthenticatedAdminModerasjonRoute
  AuthenticatedAdminPromoteringerRoute: typeof AuthenticatedAdminPromoteringerRoute
  AuthenticatedAdminVippsWebhooksRoute: typeof AuthenticatedAdminVippsWebhooksRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminBrukereRoute: AuthenticatedAdminBrukereRoute,
    AuthenticatedAdminKategorierRoute: AuthenticatedAdminKategorierRoute,
    AuthenticatedAdminModerasjonRoute: AuthenticatedAdminModerasjonRoute,
    AuthenticatedAdminPromoteringerRoute: AuthenticatedAdminPromoteringerRoute,
    AuthenticatedAdminVippsWebhooksRoute: AuthenticatedAdminVippsWebhooksRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedFavoritterRoute: typeof AuthenticatedFavoritterRoute
  AuthenticatedMineSokRoute: typeof AuthenticatedMineSokRoute
  AuthenticatedNyAnnonseRoute: typeof AuthenticatedNyAnnonseRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedBekrefterPromoIdRoute: typeof AuthenticatedBekrefterPromoIdRoute
  AuthenticatedKvitteringPromoIdRoute: typeof AuthenticatedKvitteringPromoIdRoute
  AuthenticatedMeldingerIdRoute: typeof AuthenticatedMeldingerIdRoute
  AuthenticatedMeldingerIndexRoute: typeof AuthenticatedMeldingerIndexRoute
  AuthenticatedMineAnnonserIndexRoute: typeof AuthenticatedMineAnnonserIndexRoute
  AuthenticatedMineAnnonserIdRedigerRoute: typeof AuthenticatedMineAnnonserIdRedigerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedFavoritterRoute: AuthenticatedFavoritterRoute,
  AuthenticatedMineSokRoute: AuthenticatedMineSokRoute,
  AuthenticatedNyAnnonseRoute: AuthenticatedNyAnnonseRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedBekrefterPromoIdRoute: AuthenticatedBekrefterPromoIdRoute,
  AuthenticatedKvitteringPromoIdRoute: AuthenticatedKvitteringPromoIdRoute,
  AuthenticatedMeldingerIdRoute: AuthenticatedMeldingerIdRoute,
  AuthenticatedMeldingerIndexRoute: AuthenticatedMeldingerIndexRoute,
  AuthenticatedMineAnnonserIndexRoute: AuthenticatedMineAnnonserIndexRoute,
  AuthenticatedMineAnnonserIdRedigerRoute:
    AuthenticatedMineAnnonserIdRedigerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  KaupetCodeRoute: KaupetCodeRoute,
  AnnonserRoute: AnnonserRoute,
  AuthRoute: AuthRoute,
  PersonvernRoute: PersonvernRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VilkarRoute: VilkarRoute,
  AnnonseListingIdRoute: AnnonseListingIdRoute,
  BrukerIdRoute: BrukerIdRoute,
  ApiPublicPushDispatchRoute: ApiPublicPushDispatchRoute,
  ApiPublicVippsWebhookRoute: ApiPublicVippsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
