-- Privacy-safe, first-party funnel telemetry. Events are deliberately limited
-- to a small allowlist and contain no free text, search terms, IP addresses or
-- stable user identifiers. The session id is generated by the client and
-- expires with the browser/app session.

CREATE TABLE public.product_events (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  session_id uuid NOT NULL,
  event_name text NOT NULL CHECK (event_name IN (
    'auth_started', 'auth_completed',
    'search_opened', 'search_submitted', 'search_zero_results',
    'listing_opened', 'contact_started', 'favorite_toggled',
    'listing_creation_started', 'listing_creation_step_completed',
    'listing_published', 'onboarding_completed'
  )),
  platform text NOT NULL CHECK (platform IN ('web', 'ios', 'android')),
  path text NOT NULL CHECK (length(path) BETWEEN 1 AND 160),
  properties jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT product_events_properties_object CHECK (jsonb_typeof(properties) = 'object'),
  CONSTRAINT product_events_properties_size CHECK (pg_column_size(properties) <= 2048)
);

CREATE INDEX product_events_created_at_idx ON public.product_events (created_at DESC);
CREATE INDEX product_events_name_created_at_idx
  ON public.product_events (event_name, created_at DESC);

ALTER TABLE public.product_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.product_events FROM PUBLIC, anon, authenticated;

CREATE TABLE public.product_event_rate_limits (
  key_hash text PRIMARY KEY CHECK (length(key_hash) = 64),
  window_started_at timestamptz NOT NULL DEFAULT now(),
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0)
);

ALTER TABLE public.product_event_rate_limits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.product_event_rate_limits FROM PUBLIC, anon, authenticated;

CREATE FUNCTION public.log_product_event_rate_limited(
  _key_hash text,
  _session_id uuid,
  _event_name text,
  _platform text,
  _path text,
  _properties jsonb DEFAULT '{}'::jsonb
) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  current_attempts integer;
BEGIN
  IF length(_key_hash) <> 64
    OR _event_name NOT IN (
      'auth_started', 'auth_completed',
      'search_opened', 'search_submitted', 'search_zero_results',
      'listing_opened', 'contact_started', 'favorite_toggled',
      'listing_creation_started', 'listing_creation_step_completed',
      'listing_published', 'onboarding_completed'
    )
    OR _platform NOT IN ('web', 'ios', 'android')
    OR length(_path) NOT BETWEEN 1 AND 160
    OR jsonb_typeof(_properties) <> 'object'
    OR pg_column_size(_properties) > 2048 THEN
    RAISE EXCEPTION 'Invalid product event input';
  END IF;

  INSERT INTO public.product_event_rate_limits AS limits
    (key_hash, window_started_at, attempts)
  VALUES (_key_hash, now(), 1)
  ON CONFLICT (key_hash) DO UPDATE SET
    attempts = CASE
      WHEN limits.window_started_at < now() - interval '10 minutes' THEN 1
      ELSE limits.attempts + 1
    END,
    window_started_at = CASE
      WHEN limits.window_started_at < now() - interval '10 minutes' THEN now()
      ELSE limits.window_started_at
    END
  RETURNING attempts INTO current_attempts;

  IF current_attempts <= 180 THEN
    INSERT INTO public.product_events
      (session_id, event_name, platform, path, properties)
    VALUES
      (_session_id, _event_name, _platform, _path, _properties);
  END IF;

  -- Keep the dataset intentionally short-lived and self-cleaning.
  DELETE FROM public.product_events WHERE created_at < now() - interval '90 days';
  DELETE FROM public.product_event_rate_limits
    WHERE window_started_at < now() - interval '1 day';
END;
$$;

REVOKE ALL ON FUNCTION public.log_product_event_rate_limited(
  text, uuid, text, text, text, jsonb
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.log_product_event_rate_limited(
  text, uuid, text, text, text, jsonb
) TO service_role;

